# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diff_level',
            field=models.CharField(choices=[('5', 'Very Hard'), ('4', 'Hard'), ('3', 'Average'), ('2', 'Easy'), ('1', 'Very Easy')], default='5', max_length=1),
        ),
    ]
