# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_time',
            field=models.IntegerField(default=60),
        ),
    ]
