# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSetter', '0002_test_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
