# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestSetter', '0003_test_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
