# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-02 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestSetter', '0004_auto_20200502_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='url',
            new_name='test_url',
        ),
    ]
