# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-18 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20191118_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstest',
            name='completion_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 6, 40, 44, 752411)),
        ),
    ]
