# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-02 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20200502_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstest',
            name='completion_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 18, 32, 25, 224847)),
        ),
    ]
